apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo-stateful
spec:
  selector:
    matchLabels:
      app: second-todolist
  serviceName: stateful-service
  template:
    metadata:
      labels:
        app: second-todolist
    spec:
      volumes:
        - name: todolist-stateful-volume
          persistentVolumeClaim:
            claimName: todolist-pvc
      containers:
        - name: todolist2
          image: harness/todolist-sample:latest 
          ports:
            - containerPort: 80
          volumeMounts:
            - name: todolist-stateful-volume
              mountPath: "/usr/share/nginx/html"
  replicas: 3
