apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-todolist
spec:
  selector:
    matchLabels:
      app: first-todolist
  template:
    metadata:
      labels:
        app: first-todolist
    spec:
      containers:
        - name: todo-list
          image: harness/todolist-sample:latest
          ports:
            - containerPort: 8080
  replicas: 3 
