apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: nginxapp
  serviceName: nginx-sp
  template:
    metadata:
      labels:
        app: nginxapp
    spec: 
      volumes:
        - name: webapp-pv
          persistentVolumeClaim:
            claimName: webapp-pvc
      volumes:
        - name: webapp-pv
          configMap:
            name: nginx-cm
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          env:
            - name: WEBAPP_TITLE
              valueFrom:
                configMapKeyRef:
                  name: nginx-cm
                  key: WEBAPP_TITLE
            - name: WEBAPP_DESCRIPTION
              valueFrom:
                configMapKeyRef:
                  name: nginx-cm
                  key: WEBAPP_DESCRIPTION
          volumeMounts:
            - name: webapp-pv
              mountPath: "/usr/share/nginx/html"
  replicas: 3

