apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        role: slave
    spec:
      containers:
        - name: redisslave
          image: ibmcom/guestbook-redis-slave:v2
          ports:
            - containerPort: 6379
  replicas: 2
