apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-slave
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: stateful-service
  template:
    metadata:
      labels:
        app: redis
        role: slave
    spec:
      volumes:
        - name: pvc-volume
          persistentVolumeClaim:
            claimName: pvc
      containers:
        - name: redisslave
          image: ibmcom/guestbook-redis-slave:v2                   
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: pvc-volume
              mountPath: "/usr/share/"
  replicas: 2
