apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    app: redis
    role: slave
spec:
  selector:
    app: redis
    role: slave
  ports:
  - name: rediss
    port: 6379
    targetPort: 6379
