apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
spec:
  selector:
    app: redis
    role: master
  ports:
  - name: redism
    port: 6379
    targetPort: 6379
